name: CI # Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - test
      - rustfmt
      # - clippy
      - docs
      # - semver
      - udeps
    steps:
      - run: exit 0

  test:
    name: Build & test
    needs: [rustfmt]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build all targets with all features
        run: cargo build --all-targets --all-features --workspace

      - name: Run tests with all features
        run: cargo test --all-features --workspace

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all --check

  # TODO: Fix clippy warnings
  # clippy:
  #   name: Clippy
  #   needs: [rustfmt]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5
  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: clippy
  #     - uses: Swatinem/rust-cache@v2
  #     - name: Clippy check
  #       run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  docs:
    name: Docs
    needs: [rustfmt, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --all-features --workspace --examples

  udeps:
    needs: [rustfmt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@cargo-udeps

      - uses: Swatinem/rust-cache@v2

      - name: Check unused dependencies on default features
        run: cargo udeps --all-targets

      - name: Check unused dependencies on full features
        run: cargo udeps --all-features --all-targets

  # TODO: uncomment this after all crates are published
  # semver:
  #   name: semver
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Check semver
  #       uses: obi1kenobi/cargo-semver-checks-action@v2
